return {
	keyCommands = {
		{down = fcs_commands.Switch_ANTISKID, up = fcs_commands.Switch_ANTISKID, cockpit_device_id=devices.FLIGHTCONTROLS, value_down=1.0, value_up=0.5, name = _('Anti-Skid TEST else ON'), category = _('Joystick Switch Abstractions')},

		{down = acnip_commands.Switch_IFF_OPMODE, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('IFF Operational Mode Switch EMER'), category = _('IFF')},
		{down = acnip_commands.Switch_IFF_OPMODE, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('IFF Operational Mode Switch NORM'), category = _('IFF')}, 

		{down = acnip_commands.Switch_IFF_CRYPTO, up = acnip_commands.Switch_IFF_CRYPTO, cockpit_device_id = devices.ACNIP, value_down = -0.5, value_up = 0, name = _('IFF Crypto Mode Switch HOLD else NORM'), category = _('IFF')},
		{down = acnip_commands.Switch_IFF_CRYPTO, up = acnip_commands.Switch_IFF_CRYPTO, cockpit_device_id = devices.ACNIP, value_down = 0.5, value_up = 0, name = _('IFF Crypto Mode Switch ZERO else NORM'), category = _('IFF')},

		{down = edp_commands.BRT_Knob, cockpit_device_id = devices.EDP, value_down = 1.0, name = _('EDP Brightness 100%'), category = _('Engine & Fuel')}, 
		{down = edp_commands.BRT_Knob, cockpit_device_id = devices.EDP, value_down = 0.66, name = _('EDP Brightness 66%'), category = _('Engine & Fuel')},
		{down = edp_commands.BRT_Knob, cockpit_device_id = devices.EDP, value_down = 0.5, name = _('EDP Brightness 50%'), category = _('Engine & Fuel')},
		{down = edp_commands.BRT_Knob, cockpit_device_id = devices.EDP, value_down = 0.33, name = _('EDP Brightness 33%'), category = _('Engine & Fuel')},
		{down = edp_commands.BRT_Knob, cockpit_device_id = devices.EDP, value_down = 0.0, name = _('EDP Brightness 0%'), category = _('Engine & Fuel')}, 

		{down = rwr_commands.Knob_RWR, cockpit_device_id = devices.RWRCONTROL, value_down = 0.0, name = _('RWR Volume Knob Off'), category = _('ECM Control panel')},

		{down = engine_commands.Switch_JPTL, up = engine_commands.Switch_JPTL, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('JPTL Switch Off else On'), category = _('Engine & Fuel')},
		{down = engine_commands.Switch_JPTL, up = engine_commands.Switch_JPTL, cockpit_device_id = devices.DECS, value_down = 0, value_up = 1, name = _('JPTL Switch On else Off'), category = _('Engine & Fuel')},
		{down = engine_commands.Switch_MAN_FUEL, up = engine_commands.Switch_MAN_FUEL, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('Manual Fuel Switch On else Off'), category = _('Engine & Fuel')},
		{down = engine_commands.Switch_MAN_FUEL, up = engine_commands.Switch_MAN_FUEL, cockpit_device_id = devices.DECS, value_down = 0, value_up = 1, name = _('Manual Fuel Switch Off else On'), category = _('Engine & Fuel')},

		{down = acnip_commands.Switch_MODE, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('ACNIP Mode Switch MAN'), category = _('ACNIP')},
		{down = acnip_commands.Switch_MODE, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('ACNIP Mode Switch UFC'), category = _('ACNIP')}, 

		{down = acnip_commands.Switch_KY1, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('KY-1 Cipher Type Selector Switch DIPH'), category = _('ACNIP')},
		{down = acnip_commands.Switch_KY1, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('KY-1 Cipher Type Selector Switch BB'), category = _('ACNIP')}, 

		{down = acnip_commands.Switch_KY2, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('KY-2 Cipher Type Selector Switch DIPH'), category = _('ACNIP')},
		{down = acnip_commands.Switch_KY2, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('KY-2 Cipher Type Selector Switch BB'), category = _('ACNIP')}, 

		{down = acnip_commands.Switch_KY1_MODE, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('KY-1 Code/Mode Switch Code'), category = _('ACNIP')},
		{down = acnip_commands.Switch_KY1_MODE, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('KY-1 Code/Mode Switch Mode'), category = _('ACNIP')}, 

		{down = acnip_commands.Switch_KY2_MODE, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('KY-2 Code/Mode Switch Code'), category = _('ACNIP')},
		{down = acnip_commands.Switch_KY2_MODE, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('KY-2 Code/Mode Switch Mode'), category = _('ACNIP')}, 

		{down = acnip_commands.Switch_PRGM, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('ACNIP Radio Selector Switch Program 1'), category = _('ACNIP')},
		{down = acnip_commands.Switch_PRGM, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('ACNIP Radio Selector Switch Program 2'), category = _('ACNIP')},

		{down = acnip_commands.Switch_KY_ZERO, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('KY-58 Codes Clear Switch Zero'), category = _('ACNIP')},
		{down = acnip_commands.Switch_KY_ZERO, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('KY-58 Codes Clear Switch Norm'), category = _('ACNIP')},

		{down = acnip_commands.Switch_KY_RVI, cockpit_device_id = devices.ACNIP, value_down = 1.0, name = _('KY-58 Remote Codes Load Switch RV1'), category = _('ACNIP')},
		{down = acnip_commands.Switch_KY_RVI, cockpit_device_id = devices.ACNIP, value_down = 0.0, name = _('KY-58 Remote Codes Load Switch OPR'), category = _('ACNIP')}, 
		{down = acnip_commands.Switch_KY_RVI, cockpit_device_id = devices.ACNIP, value_down = -1.0, name = _('KY-58 Remote Codes Load Switch RV2'), category = _('ACNIP')}, 

		{down = acnip_commands.Knob_AUX_VOL, cockpit_device_id = devices.INTERCOM, value_down = 1.0, name = _('ICS Aux Volume Knob 100%'), category = _('ACNIP')}, 
		{down = acnip_commands.Knob_AUX_VOL, cockpit_device_id = devices.INTERCOM, value_down = 0.66, name = _('ICS Aux Volume Knob 66%'), category = _('ACNIP')},
		{down = acnip_commands.Knob_AUX_VOL, cockpit_device_id = devices.INTERCOM, value_down = 0.5, name = _('ICS Aux Volume Knob 50%'), category = _('ACNIP')},
		{down = acnip_commands.Knob_AUX_VOL, cockpit_device_id = devices.INTERCOM, value_down = 0.33, name = _('ICS Aux Volume Knob 33%'), category = _('ACNIP')},
		{down = acnip_commands.Knob_AUX_VOL, cockpit_device_id = devices.INTERCOM, value_down = 0.0, name = _('ICS Aux Volume Knob 0%'), category = _('ACNIP')}, 

		{down = acnip_commands.Knob_GND_VOL, cockpit_device_id = devices.INTERCOM, value_down = 1.0, name = _('ICS Ground Volume Knob 100%'), category = _('ACNIP')}, 
		{down = acnip_commands.Knob_GND_VOL, cockpit_device_id = devices.INTERCOM, value_down = 0.66, name = _('ICS Ground Volume Knob 66%'), category = _('ACNIP')},
		{down = acnip_commands.Knob_GND_VOL, cockpit_device_id = devices.INTERCOM, value_down = 0.5, name = _('ICS Ground Volume Knob 50%'), category = _('ACNIP')},
		{down = acnip_commands.Knob_GND_VOL, cockpit_device_id = devices.INTERCOM, value_down = 0.33, name = _('ICS Ground Volume Knob 33%'), category = _('ACNIP')},
		{down = acnip_commands.Knob_GND_VOL, cockpit_device_id = devices.INTERCOM, value_down = 0.0, name = _('ICS Ground Volume Knob 0%'), category = _('ACNIP')}, 

		{down = acnip_commands.Switch_MIC, cockpit_device_id = devices.INTERCOM, value_down = 1.0, name = _('ICS Mic Operational Mode Switch TEL'), category = _('ACNIP')}, 
		{down = acnip_commands.Switch_MIC, cockpit_device_id = devices.INTERCOM, value_down = 0.5, name = _('ICS Mic Operational Mode Switch HOT MIC'), category = _('ACNIP')},
		{down = acnip_commands.Switch_MIC, cockpit_device_id = devices.INTERCOM, value_down = 0.0, name = _('ICS Mic Operational Mode Switch COLD MIC'), category = _('ACNIP')}, 

		{down = int_light_commands.Knob_Instr_Lights, cockpit_device_id = devices.LTINT, value_down = 1.0, name = _('Instruments Lights Knob 100%'), category = _('Internal Lights')}, 
		{down = int_light_commands.Knob_Instr_Lights, cockpit_device_id = devices.LTINT, value_down = 0.66, name = _('Instruments Lights Knob 66%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Instr_Lights, cockpit_device_id = devices.LTINT, value_down = 0.5, name = _('Instruments Lights Knob 50%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Instr_Lights, cockpit_device_id = devices.LTINT, value_down = 0.33, name = _('Instruments Lights Knob 33%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Instr_Lights, cockpit_device_id = devices.LTINT, value_down = 0.0, name = _('Instruments Lights Knob 0%'), category = _('Internal Lights')}, 

		{down = int_light_commands.Knob_Console_Lights, cockpit_device_id = devices.LTINT, value_down = 1.0, name = _('Console Lights Knob 100%'), category = _('Internal Lights')}, 
		{down = int_light_commands.Knob_Console_Lights, cockpit_device_id = devices.LTINT, value_down = 0.66, name = _('Console Lights Knob 66%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Console_Lights, cockpit_device_id = devices.LTINT, value_down = 0.5, name = _('Console Lights Knob 50%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Console_Lights, cockpit_device_id = devices.LTINT, value_down = 0.33, name = _('Console Lights Knob 33%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Console_Lights, cockpit_device_id = devices.LTINT, value_down = 0.0, name = _('Console Lights Knob 0%'), category = _('Internal Lights')}, 

		{down = int_light_commands.Knob_Flood_Lights, cockpit_device_id = devices.LTINT, value_down = 1.0, name = _('Flood Lights Knob 100%'), category = _('Internal Lights')}, 
		{down = int_light_commands.Knob_Flood_Lights, cockpit_device_id = devices.LTINT, value_down = 0.66, name = _('Flood Lights Knob 66%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Flood_Lights, cockpit_device_id = devices.LTINT, value_down = 0.5, name = _('Flood Lights Knob 50%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Flood_Lights, cockpit_device_id = devices.LTINT, value_down = 0.33, name = _('Flood Lights Knob 33%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Flood_Lights, cockpit_device_id = devices.LTINT, value_down = 0.0, name = _('Flood Lights Knob 0%'), category = _('Internal Lights')}, 

		{down = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, value_down = 1.0, name = _('Annunciator Lights Knob 100%'), category = _('Internal Lights')}, 
		{down = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, value_down = 0.66, name = _('Annunciator Lights Knob 66%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, value_down = 0.5, name = _('Annunciator Lights Knob 50%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, value_down = 0.33, name = _('Annunciator Lights Knob 33%'), category = _('Internal Lights')},
		{down = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, value_down = 0.0, name = _('Annunciator Lights Knob 0%'), category = _('Internal Lights')}, 

		{down = ecs_commands.Knob_TEMP, cockpit_device_id = devices.ECS, value_down = 1.0, name = _('ECS Temperature Control 100%'), category = _('Environmental Control')}, 
		{down = ecs_commands.Knob_TEMP, cockpit_device_id = devices.ECS, value_down = 0.66, name = _('ECS Temperature Control 66%'), category = _('Environmental Control')},
		{down = ecs_commands.Knob_TEMP, cockpit_device_id = devices.ECS, value_down = 0.5, name = _('ECS Temperature Control 50%'), category = _('Environmental Control')},
		{down = ecs_commands.Knob_TEMP, cockpit_device_id = devices.ECS, value_down = 0.33, name = _('ECS Temperature Control 33%'), category = _('Environmental Control')},
		{down = ecs_commands.Knob_TEMP, cockpit_device_id = devices.ECS, value_down = 0.0, name = _('ECS Temperature Control 0%'), category = _('Environmental Control')}, 

		{down = hud_commands.VideoBRTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 1.0, name = _('HUD Video Brightness Control 100%'), category = _('HUD Control')}, 
		{down = hud_commands.VideoBRTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 0.66, name = _('HUD Video Brightness Control 66%'), category = _('HUD Control')},
		{down = hud_commands.VideoBRTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 0.5, name = _('HUD Video Brightness Control 50%'), category = _('HUD Control')},
		{down = hud_commands.VideoBRTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 0.33, name = _('HUD Video Brightness Control 33%'), category = _('HUD Control')},
		{down = hud_commands.VideoBRTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 0.0, name = _('HUD Video Brightness Control 0%'), category = _('HUD Control')}, 

		{down = hud_commands.VideoCONTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 1.0, name = _('HUD Video Contrast Control 100%'), category = _('HUD Control')}, 
		{down = hud_commands.VideoCONTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 0.66, name = _('HUD Video Contrast Control 66%'), category = _('HUD Control')},
		{down = hud_commands.VideoCONTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 0.5, name = _('HUD Video Contrast Control 50%'), category = _('HUD Control')},
		{down = hud_commands.VideoCONTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 0.33, name = _('HUD Video Contrast Control 33%'), category = _('HUD Control')},
		{down = hud_commands.VideoCONTKnob, cockpit_device_id = devices.HUDCONTROL, value_down = 0.0, name = _('HUD Video Contrast Control 0%'), category = _('HUD Control')}, 

		-- Toggle Switches added by VEAF
		{down = fcs_commands.Switch_FLAP_SELECT, up = fcs_commands.Switch_FLAP_SELECT, cockpit_device_id = devices.VREST, value_down = 1, value_up = 0.5, name = _('Flaps CRUISE/AUTO Three Position'), category = { _('Toggle Switches'), _('VSTOL Controls'), _('Landing Gear/Flaps Control Panel')}},
		{down = fcs_commands.Switch_FLAP_SELECT, up = fcs_commands.Switch_FLAP_SELECT, cockpit_device_id = devices.VREST, value_down = 0, value_up = 0.5, name = _('Flaps STOVL/AUTO Three Position'), category = { _('Toggle Switches'), _('VSTOL Controls'), _('Landing Gear/Flaps Control Panel')}},
		{down = smc_commands.Switch_Master_Arm, up = smc_commands.Switch_Master_Arm, cockpit_device_id = devices.SMC, value_down = 1, value_up = 0, name = _('Master Arm Two Position'), category = { _('Toggle Switches'), _('Armament Control')}},
		{down = engine_commands.Switch_H20, up = engine_commands.Switch_H20, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0.5, name = _('H2O TO/OFF Three Position'), category = { _('Toggle Switches'), _('VSTOL Controls')}},
		{down = engine_commands.Switch_H20, up = engine_commands.Switch_H20, cockpit_device_id = devices.DECS, value_down = 0, value_up = 0.5, name = _('H2O LD/OFF Three Position'), category = { _('Toggle Switches'), _('VSTOL Controls')}},
		{down = fcs_commands.Handle_GEAR_LEVER, up = fcs_commands.Handle_GEAR_LEVER, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0, name = _('Landing Gear Lever Two Position'), category = { _('Toggle Switches'), _('Hydraulic & Mechanical'), _('Landing Gear/Flaps Control Panel')}},
		{down = ext_light_commands.Switch_EXT_LT_NORM_NVG, up = ext_light_commands.Switch_EXT_LT_NORM_NVG, cockpit_device_id = devices.LTEXT, value_down = 1, value_up = 0.5, name = _('EXT LT NVG/NORM Three Position'), category = { _('Toggle Switches'), _('Exterior Lights')}},
		{down = ext_light_commands.Switch_EXT_LT_NORM_NVG, up = ext_light_commands.Switch_EXT_LT_NORM_NVG, cockpit_device_id = devices.LTEXT, value_down = 0, value_up = 0.5, name = _('EXT LT OFF/NVG Three Position'), category = { _('Toggle Switches'), _('Exterior Lights')}},
		{down = ext_light_commands.Switch_LANDING_LT, up = ext_light_commands.Switch_LANDING_LT, cockpit_device_id = devices.LTEXT, value_down = 1, value_up = 0.5, name = _('LDG LT HVR/APRCH Three Position'), category = { _('Toggle Switches'), _('Exterior Lights')}},
		{down = ext_light_commands.Switch_LANDING_LT, up = ext_light_commands.Switch_LANDING_LT, cockpit_device_id = devices.LTEXT, value_down = 0, value_up = 0.5, name = _('LDG LT OFF/HVR Three Position'), category = { _('Toggle Switches'), _('Exterior Lights')}},
		{down = ext_light_commands.Switch_ANTI_COLL_LT, up = ext_light_commands.Switch_ANTI_COLL_LT, cockpit_device_id = devices.LTEXT, value_down = 1, value_up = 0, name = _('Anti-Collision LT Two Position'), category = { _('Toggle Switches'), _('Exterior Lights')}},
		{down = ext_light_commands.Switch_POS_LT, up = ext_light_commands.Switch_POS_LT, cockpit_device_id = devices.LTEXT, value_down = 1, value_up = 0.5, name = _('POS LT BRT/DIM Three Position'), category = { _('Toggle Switches'), _('Exterior Lights')}},
		{down = ext_light_commands.Switch_POS_LT, up = ext_light_commands.Switch_POS_LT, cockpit_device_id = devices.LTEXT, value_down = 0, value_up = 0.5, name = _('POS LT OFF/DIM Three Position'), category = { _('Toggle Switches'), _('Exterior Lights')}},
		{down = ext_light_commands.Knob_FORM_LT, up = ext_light_commands.Knob_FORM_LT, cockpit_device_id = devices.LTEXT, value_down = 1, value_up = 0, name = _('FORM LT Two Position knob'), category = { _('Toggle Switches'), _('Exterior Lights')}},
		{down = fcs_commands.Switch_ANTISKID, up = fcs_commands.Switch_ANTISKID, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.5, value_up = 0, name = _('Antiskid ON/NWS Two Position'), category = { _('Toggle Switches'), _('VSTOL Controls'), _('Landing Gear/Flaps Control Panel')}},
		{down = fcs_commands.Switch_ANTISKID, up = fcs_commands.Switch_ANTISKID, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0.5, name = _('Antiskid TEST/ON Three Position'), category = { _('Toggle Switches'), _('VSTOL Controls'), _('Landing Gear/Flaps Control Panel')}},
		{down = fcs_commands.Switch_ANTISKID, up = fcs_commands.Switch_ANTISKID, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0, value_up = 0.5, name = _('Antiskid NWS/ON Three Position'), category = { _('Toggle Switches'), _('VSTOL Controls'), _('Landing Gear/Flaps Control Panel')}},
		{down = hud_commands.AltitudeSelector, up = hud_commands.AltitudeSelector, cockpit_device_id = devices.HUDCONTROL, value_down = 0, value_up = 1, name = _('HUD Altitude Selector Baro/RDR Two Position'), category = { _('Toggle Switches'), _('HUD Control')}},
		{down = hud_commands.RejectSwitch, up = hud_commands.RejectSwitch, cockpit_device_id = devices.HUDCONTROL, value_down = 0, value_up = 0.5, name = _('HUD Reject Switch Norm/Rej 1 Three Position'), category = { _('Toggle Switches'), _('HUD Control')}},
		{down = hud_commands.RejectSwitch, up = hud_commands.RejectSwitch, cockpit_device_id = devices.HUDCONTROL, value_down = 1, value_up = 0.5, name = _('HUD Reject Switch Rej 2/Rej 1 Three Position'), category = { _('Toggle Switches'), _('HUD Control')}},
		{down = hud_commands.DisplayModeSwitch, up = hud_commands.DisplayModeSwitch, cockpit_device_id = devices.HUDCONTROL, value_down = 0, value_up = 0.5, name = _('HUD Mode Selector Day/Auto Three Position'), category = { _('Toggle Switches'), _('HUD Control')}},
		{down = hud_commands.DisplayModeSwitch, up = hud_commands.DisplayModeSwitch, cockpit_device_id = devices.HUDCONTROL, value_down = 1, value_up = 0.5, name = _('HUD Mode Selector Night/Auto Three Position'), category = { _('Toggle Switches'), _('HUD Control')}},
		{down = int_light_commands.Knob_Instr_Lights, up = int_light_commands.Knob_Instr_Lights, cockpit_device_id = devices.LTINT, value_down = 1, value_up = 0, name = _('Instrument Lights Two Position knob'), category = { _('Toggle Switches'), _('Internal Lights')}},
		{down = int_light_commands.Knob_Console_Lights, up = int_light_commands.Knob_Console_Lights, cockpit_device_id = devices.LTINT, value_down = 1, value_up = 0, name = _('Console Lights Two Position knob'), category = { _('Toggle Switches'), _('Internal Lights')}},
		{down = int_light_commands.Knob_Flood_Lights, up = int_light_commands.Knob_Flood_Lights, cockpit_device_id = devices.LTINT, value_down = 1, value_up = 0, name = _('Flood Lights Two Position Knob'), category = { _('Toggle Switches'), _('Internal Lights')}},	
		{down = psp_commands.Switch_OXY, up = psp_commands.Switch_OXY, cockpit_device_id = devices.ECS, value_down = 1, value_up = 0, name = _('Oxygen Switch Two Position'), category = { _('Toggle Switches'), _('Pilot Services Panel')}},
		{down = engine_commands.Switch_H20_DUMP, up = engine_commands.Switch_H20_DUMP, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('H2O Dump Switch Two Position'), category = { _('Toggle Switches'), _('Pilot Services Panel')}},
		{down = engine_commands.Switch_ENG_RPM, up = engine_commands.Switch_ENG_RPM, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('Engine RPM Switch Two Position'), category = { _('Toggle Switches'), _('Pilot Services Panel')}},
		{down = engine_commands.Switch_EFC, up = engine_commands.Switch_EFC, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('EFC Switch Two Position'), category = { _('Toggle Switches'), _('Pilot Services Panel')}},
		{down = engine_commands.Switch_LIDS, up = engine_commands.Switch_LIDS, cockpit_device_id = devices.VREST, value_down = 1, value_up = 0, name = _('LIDS Switch Two Position'), category = { _('Toggle Switches'), _('Pilot Services Panel')}},
		{down = engine_commands.Switch_DECS, up = engine_commands.Switch_DECS, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('DECS Switch Two Position'), category = { _('Toggle Switches'), _('Pilot Services Panel')}},
		{down = int_light_commands.Knob_Annunciator_Lights, up = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, value_down = 0.9, value_up = 0, name = _('Annunciator Lights Two Position knob'), category = { _('Toggle Switches'), _('Internal Lights')}},	
		{down = fcs_commands.Switch_SAS_YAW, up = fcs_commands.Switch_SAS_YAW, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0, name = _('SAS Yaw Two Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = fcs_commands.Switch_SAS_ROLL, up = fcs_commands.Switch_SAS_ROLL, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0, name = _('SAS Roll Two Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = fcs_commands.Switch_SAS_PITCH, up = fcs_commands.Switch_SAS_PITCH, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0, name = _('SAS Pitch Two Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = fcs_commands.Switch_ALT_HOLD, up = fcs_commands.Switch_ALT_HOLD, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0, name = _('Alt Hold Switch Two Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = fcs_commands.Switch_Q_FEEL, up = fcs_commands.Switch_Q_FEEL, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0, name = _('Q Feel Switch Two Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = fcs_commands.Switch_AFC, up = fcs_commands.Switch_AFC, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0.5, name = _('AFC Switch ON/OFF Three Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = fcs_commands.Switch_AFC, up = fcs_commands.Switch_AFC, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0, value_up = 0.5, name = _('AFC Switch RESET/OFF Three Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = engine_commands.Switch_JPTL, up = engine_commands.Switch_JPTL, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('JPTL Switch Two Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_MAN_FUEL, up = engine_commands.Switch_MAN_FUEL, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('Manual Fuel Switch Two Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_PROP, up = engine_commands.Switch_FUEL_PROP, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('Fuel Proportioner Two Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_PUMP_L, up = engine_commands.Switch_FUEL_PUMP_L, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0.5, name = _('Fuel Pump L ON/OFF Three Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_PUMP_L, up = engine_commands.Switch_FUEL_PUMP_L, cockpit_device_id = devices.DECS, value_down = 0, value_up = 0.5, name = _('Fuel Pump L DC OPR/OFF Three Position'), category = {_('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_PUMP_R, up = engine_commands.Switch_FUEL_PUMP_R, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0.5, name = _('Fuel Pump R ON/OFF Three Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_PUMP_R, up = engine_commands.Switch_FUEL_PUMP_R, cockpit_device_id = devices.DECS, value_down = 0, value_up = 0.5, name = _('Fuel Pump R DC OPR/OFF Three Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_PRESS, up = engine_commands.Switch_FUEL_PRESS, cockpit_device_id = devices.DECS, value_down = 0.5, value_up = 0, name = _('Air Refueling Probe Switch Two Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_PRESS, up = engine_commands.Switch_FUEL_PRESS, cockpit_device_id = devices.DECS, value_down = 0, value_up = 0.5, name = _('Air Refueling Probe Switch In/Out Three Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_PRESS, up = engine_commands.Switch_FUEL_PRESS, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0.5, name = _('Air Refueling Probe Switch Press/Out Three Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_DUMP_L, up = engine_commands.Switch_FUEL_DUMP_L, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('Fuel Dump L Switch Two Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = engine_commands.Switch_FUEL_DUMP_R, up = engine_commands.Switch_FUEL_DUMP_R, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('Fuel Dump R Switch Two Position'), category = { _('Toggle Switches'), _('Engine & Fuel')}},
		{down = elec_commands.Switch_BATT, up = elec_commands.Switch_BATT, cockpit_device_id = devices.ELECTRIC, value_down = 1, value_up = 0.5, name = _('Battery ON/OFF Three Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = elec_commands.Switch_BATT, up = elec_commands.Switch_BATT, cockpit_device_id = devices.ELECTRIC, value_down = 0, value_up = 0.5, name = _('Battery ALERT/OFF Three Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = elec_commands.Switch_GEN, up = elec_commands.Switch_GEN, cockpit_device_id = devices.ELECTRIC, value_down = 1, value_up = 0.5, name = _('Generator ON/OFF Three Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = elec_commands.Switch_GEN, up = elec_commands.Switch_GEN, cockpit_device_id = devices.ELECTRIC, value_down = 0, value_up = 0.5, name = _('Generator TEST/OFF Three Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = elec_commands.Switch_ENG_START, up = elec_commands.Switch_ENG_START, cockpit_device_id = devices.ELECTRIC, value_down = 1, value_up = 0, name = _('Engine Start Switch Two Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = elec_commands.Switch_APU_GEN, up = elec_commands.Switch_APU_GEN, cockpit_device_id = devices.ELECTRIC, value_down = 1, value_up = 0.5, name = _('APU Generator Switch RESET/ON Three Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = elec_commands.Switch_APU_GEN, up = elec_commands.Switch_APU_GEN, cockpit_device_id = devices.ELECTRIC, value_down = 0, value_up = 0.5, name = _('APU Generator Switch OFF/ON Three Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = elec_commands.Switch_DC_TEST, up = elec_commands.Switch_DC_TEST, cockpit_device_id = devices.ELECTRIC, value_down = 1, value_up = 0.5, name = _('DC Test Switch STBY/OFF Three Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = elec_commands.Switch_DC_TEST, up = elec_commands.Switch_DC_TEST, cockpit_device_id = devices.ELECTRIC, value_down = 0, value_up = 0.5, name = _('DC Test Switch MAIN/OFF Three Position'), category = { _('Toggle Switches'), _('Electrical Panel')}},
		{down = misc_commands.Switch_VRS_Mode, up = misc_commands.Switch_VRS_Mode, cockpit_device_id = devices.NAVFLIR, value_down = 0, value_up = 1, name = _('Video Recorder System Mode Switch AUTO/RUN Two Position'), category = { _('Toggle Switches'), _('Miscellaneous Switch Panel')}},
		{down = misc_commands.Switch_VRS_Output, up = misc_commands.Switch_VRS_Output, cockpit_device_id = devices.NAVFLIR, value_down = 0, value_up = 1, name = _('Video Recorder System Display Selector Switch MPCD/HUD Two Position'), category = { _('Toggle Switches'), _('Miscellaneous Switch Panel')}},
		{down = misc_commands.Switch_FLIR_Power, up = misc_commands.Switch_FLIR_Power, cockpit_device_id = devices.NAVFLIR, value_down = 1, value_up = 0, name = _('FLIR Power Switch Two Position'), category = { _('Toggle Switches'), _('Miscellaneous Switch Panel')}},
		{down = misc_commands.Switch_PR_HT_Mode, up = misc_commands.Switch_PR_HT_Mode, cockpit_device_id = devices.FLIGHTINSTRUMENTS, value_down = 1, value_up = 0, name = _('Probe Heat Mode Switch HT/AUTO Two Position'), category = { _('Toggle Switches'), _('Miscellaneous Switch Panel')}},
		{down = smc_commands.Switch_IR_COOL, up = smc_commands.Switch_IR_COOL, cockpit_device_id = devices.SMC,value_down = 1, value_up = 0, name = _('Ground IR Cool Switch Two Position'), category = { _('Toggle Switches'), _('Armament Control')}},
		{down = fcs_commands.Switch_FLAP_PWR, up = fcs_commands.Switch_FLAP_PWR, cockpit_device_id = devices.VREST, value_down = 1, value_up = 0.5, name = _('Flaps Power Switch RESET/ON Three Position'), category = { _('Toggle Switches'), _('VSTOL Controls'), _('Landing Gear/Flaps Control Panel')}},
		{down = fcs_commands.Switch_FLAP_PWR, up = fcs_commands.Switch_FLAP_PWR, cockpit_device_id = devices.VREST, value_down = 0, value_up = 0.5, name = _('Flaps Power Switch OFF/ON Three Position'), category = { _('Toggle Switches'), _('VSTOL Controls'), _('Landing Gear/Flaps Control Panel')}},
		{down = fcs_commands.Switch_FLAP_PWR, up = fcs_commands.Switch_FLAP_PWR, cockpit_device_id = devices.VREST, value_down = 0.5, value_up = 0, name = _('Flaps Power Switch ON/OFF Two Position'), category = { _('Toggle Switches'), _('VSTOL Controls'), _('Landing Gear/Flaps Control Panel')}},
		{down = fcs_commands.Switch_RPS_YAW, up = fcs_commands.Switch_RPS_YAW, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1, value_up = 0.5, name = _('RPS/YAW Trim Switch TEST/ON Three Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = fcs_commands.Switch_RPS_YAW, up = fcs_commands.Switch_RPS_YAW, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0, value_up = 0.5, name = _('RPS/YAW Trim Switch OFF/ON Three Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = fcs_commands.Switch_RPS_YAW, up = fcs_commands.Switch_RPS_YAW, cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.5, value_up = 0, name = _('RPS/YAW Trim Switch ON/OFF Two Position'), category = { _('Toggle Switches'), _('Stability Augmentation & Autopilot')}},
		{down = engine_commands.Button_CMBT, up = engine_commands.Button_CMBT, cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('Combat Thrust Button'), category =  _('Engine & Fuel')},	
		{down = msc_commands.AG_Selector, up = msc_commands.NAV_Selector, cockpit_device_id = devices.MSC, value_down = 1, value_up = 1, name = _('Master Mode AG/NAV Three Position'), category =  _('Toggle Switches')},
		{down = msc_commands.VSTOL_Selector, up = msc_commands.NAV_Selector, cockpit_device_id = devices.MSC, value_down = 1, value_up = 1, name = _('Master Mode VSTOL/NAV Three Position'), category =  _('Toggle Switches')},
		{down = misc_commands.Switch_DMT_Power, up = misc_commands.Switch_DMT_Power, cockpit_device_id = devices.DMT, value_down = 1, value_up = 0, name = _('DMT ON/OFF Two Position'), category = { _('Toggle Switches'), _('Miscellaneous Switch Panel')}},	

	}
}